#' @title Generate a random password
#' 
#' @description A password is generated by sampling letters from an alphabet,
#'              consisting any combination of lowercase and uppercase
#'              characters, digits as well as special characters.
#'
#' @param length    The length of the resulting password.
#' @param lowercase Whether to include lowercase characters (logical).
#' @param uppercase Whether to include uppercase characters (logical).
#' @param digits    Whether to include digits (logical).
#' @param symbols   Whether to include special characters (logical).
#'
#' @return A password as a string.
#' 
#' @export
generatePassword <- function(length = 15, lowercase = TRUE, uppercase = TRUE,
                             digits = TRUE, symbols = TRUE) {
  # input validation
  stopifnot(
    is.numeric(length), length(length) == 1,
    is.logical(digits), length(digits) == 1,
    is.logical(symbols), length(symbols) == 1,
    is.logical(lowercase), length(lowercase) == 1,
    is.logical(uppercase), length(uppercase) == 1)
  if (length < 10) {
    warning("a short password (length ", length, ") will be weak.")
  }
  # build alphabet
  alphabet <- vector()
  if (lowercase) alphabet <- c(alphabet, letters)
  if (uppercase) alphabet <- c(alphabet, LETTERS)
  if (digits > 0) alphabet <- c(alphabet, 0:9)
  if (symbols > 0) {
    alphabet <- c(alphabet, c("?", "!", "&", "%", "$", "*", "/", "(", ")",
                              "{", "}", "[", "]", "+", "#", "~", ";", ":",
                              ".", ",", "^", "'", "=", "<", ">", "_", "-",
                              "@"))
  }
  if (length(alphabet) == 0) stop("cannot create a password with no alphabet.")
  if (length(alphabet) < 10) {
    warning("a password with a short alphabet (length ", length(alphabet),
            ") will be weak.")
  }
  # permute alphabet
  alphabet <- sample(alphabet)
  # generate password
  password <- sample(alphabet, size = length, replace = TRUE)
  return(paste(password, collapse = ""))
}